apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  # depends_on: 
  #   - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/mediabox
  prune: true
  decryption:
      provider: sops
      secretRef:
        name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: true
      - kind: Secret
        name: cluster-secrets