# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: GitRepository
# metadata:
#   name: csi-driver-smb
#   namespace: flux-system
# spec:
#   interval: 1h
#   url: https://github.com/kubernetes-csi/csi-driver-smb
#   timeout: 3m
#   ref:
#     branch: master

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts