apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - nginx.yaml
  - bitnami.yaml
  - k8s-at-home.yaml
  - podinfo.yaml
  - cloudflare.yaml
  - kubernetes-csi.yaml
  - tailscale-svc-lb.yaml
  - hajimari