apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: creds-syn
stringData:
    username: ENC[AES256_GCM,data:UjumtTjXfC0=,iv:cnqfDA6q0ENAFLadEdwuTKEf86GeHx3g/ZEOnIiKSvM=,tag:NYaGYVd6uWHm6HWhKHpVtw==,type:str]
    password: ENC[AES256_GCM,data:Y4cN1kzzZ3I=,iv:zXqYGBpfGPoE6XIXOdsQa7KQaSr6756FaSjuhllg5UI=,tag:t2K2rlROibP9YfIYgE/tyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m5ucjdyx5el33k5z548tg7x2evn4h7p2erjdc02nea62g5xe0yvszw0nmr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dlRvMXRHS3NzVkQ2SjZ2
            dExLMUNKUlVBdjEvaDRNTUQ2U3BVTy82M2o4Cm14Um01aDVKdDVnanc4V29aSi85
            N0QwNGd3QTFlUlJ6S2toREpZeURrNFkKLS0tIERVN0R2WmZUamhVVWZXL1dFMTZa
            UFU0OHlnTlJGQW1BL1kzdU95YkdTTTAKWuLtdQFMOqBuZV2TlV3diPIEIMF96yjX
            y2wRm/QQLiNuJoOBiG/iH/DRFDloO6At+SaucLlfWzHz6lE0//oFzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T16:14:38Z"
    mac: ENC[AES256_GCM,data:E1GCMaWozs2elBqIIuO513xdf2TIdPFDlAkyL2MBhc7ZSxNHKZqcxNkfRgaXSy6wGYZNJb+8RkJKdAx4Az+8yXY/74M8TAx+rkbfujWqs1JTG5uXtstwxuxLmSNv8gLtrUhB143fnvb5qJg5BAx2HXaDGM9Bz8MlRWAWU0odFJ8=,iv:puOg/+bx/nYYatu/WwAV+iZA8cr3Tz+90hXB0JGjQmM=,tag:3v4/16ArF2gpUMrq+gjCSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
