# # TODO:
# # - config volume
# # - decide structure of movies/tv/downloads

# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: pvc-config
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 25Gi
#   volumeName: pv-config
#   storageClassName: smb
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-config
# spec:
#   capacity:
#     storage: 25Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: smb
#   mountOptions:
#     - dir_mode=0777
#     - file_mode=0777
#     - noserverino
#   csi:
#     driver: smb.csi.k8s.io
#     readOnly: false
#     volumeHandle: pv-config-MTQ5NTgK  #echo $RANDOM | base64
#     volumeAttributes:
#       source: "//192.168.2.31/k8s"
#     nodeStageSecretRef:
#       name: creds-syn
#       namespace: smb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 25Gi