apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lb
  namespace: ingress-nginx
  # annotations:
  #   meta.helm.sh/release-name: ingress-nginx
  #   meta.helm.sh/release-namespace: ingress-nginx
  # labels:
  #   app.kubernetes.io/component: controller
  #   app.kubernetes.io/instance: ingress-nginx
  #   app.kubernetes.io/managed-by: Helm
  #   app.kubernetes.io/name: ingress-nginx
  #   app.kubernetes.io/part-of: ingress-nginx
  #   app.kubernetes.io/version: 1.3.1
  #   helm.sh/chart: ingress-nginx-4.2.5
  #   helm.toolkit.fluxcd.io/name: nginx
  #   helm.toolkit.fluxcd.io/namespace: flux-system
spec:
  type: LoadBalancer
  loadBalancerClass: "svc-lb.tailscale.iptables.sh/lb"
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx