apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  targetNamespace: ingress-nginx
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      # version: "4.0.19"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller:
      service:
        type: ClusterIP
        # external: 
        #   enabled: false
        # internal: 
        #   enabled: true
      ingressClassResource:
        default: true
        enabled: true
      setAsDefaultIngress: true
      watchIngressWithoutClass: true
      dnsPolicy: ClusterFirstWithHostNet
      publishService:
        enabled: true
    defaultBackend:
      enabled: true
  
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        # Array of inline strategic merge patch definitions as YAML object.
        # Note, this is a YAML object and not a string, to avoid syntax
        # indention errors.
        patchesStrategicMerge:
          - kind: Service
            apiVersion: v1
            metadata:
              name: ingress-nginx-controller
              namespace: ingress-nginx
            spec:
              type: LoadBalancer
              loadBalancerClass: svc-lb.tailscale.iptables.sh/lb
              allocateLoadBalancerNodePorts: false