apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgB3pPTsea/yEw985kEACkq1fTbCAiwFBlIic/++5Hs6yllMNJI/pHsYSV0MWvZM1Ua15gFDzEsukK4pKUjzmCbEjnfAjCUadBItBsDDuVyKq8AR7AKqAgiZGZe3Yi6irrKxC3a/Oxrez6KjSSZrLHYEAMhV72q+1nfiZ1FDLBdFgVXXtzczwY/Uq76Uf0mTBiX7KybZF205Ocs4Ickr/0mVgXWPRlINPGnpyvY2PSFrSLyPMdsRc/gBd7lxrwEDGqGFX+hSfkAvf+gpTjy+UDJT11nwyac9IV1FnYcHxL8Zo+0uNCO4OpLpZGWWJMcMsJjDxBn+8JU4It+hnvmUsVXp/YhdDejj+9/yuyb9Fe1V7ByJwXg0ePboFhifRzJYbKYgkVaGgJ9t7oTFNuCbelrRwhWMYefDIPRcVH1Z/vxERsilHdXkELYUCOClApq97jaLGeT1aPK4CEDyOvWUUFB9IAUBNm4WK7iqanyNZNE+BaYypQ24tu85iEWbvPmQTi8XU8vNcYJnDtL7gg48XHFN12Lo8mlHrvvnXlrY1cvMe6Uwzr6Zw0nwJIH2eIn9laiD6TapvUgqXpvEryWkPgo0gHakHL8VYtKYAGyVTbR1Aow9jhRaNcfz3bckaIm3PtTYiwu9cv9U4WE2S6yrCMoMPUJ4rSRFBlKP5/24gqZOk2HLgNnwmCxmlkZYpEMtM7u7cRp6YWLCOQwq9IV0QwM60PWqZqEiSTi8qUV4sDbckaTdMuseZITKfVIHjEFu7XMVi5RhcD4G/fqm1GWmnbjlYicSXQVIC4R7ACc/KzA3mb4NdWEAovsTj81aGP25eliOVQSH3wFDCyCjzoYZfZt0dQwnW3iW7EBUOmtNLEDndOnbahuf+r4smpTQ6NOhXF0kjWIKSLCtGUanqX3zHJqiC1qb+E/4422ariQAlItXmZRagX2+GcNZBtyYxkiy9zApkWKuwY0Yd/5pqAXcCR5G74IJ3I5eZIn10ORwW39mw4Kw2Fo3ODtZ03VWUC3AAIFe3jX/us0YqxQorEfI6oHaakqJ4DNxQazoTHvLdakWjU+IDcHo+Z524OYkRxnilgz7+Na4f+GrFd0wUuuNbeHiFu51HVAjTiuoB1RAtp0wnB8Idln3VAJNQsWo0nG+NtM33AAdv9aZgvWzCPZpBLdafimWNCfpx6dsirfm2lkly3GiMllbHwRp88VTTPfdCCNUimIYbKm/BjNfOAopYqwpW0prdI1eUgWS1LnYnH7CnFEUsYEDIA20NEos+HIj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: client-info-secret
      namespace: synology-csi

