apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  # - media
  # - sonarr
  # - radarr
  # - jackett
  # - transmission
  # - requesterr
  # - site
  # - tandoor
  
patchesStrategicMerge:
  - podinfo-values.yaml