apiVersion: v1
kind: Secret
metadata:
  name: cifs-csi-credentials
  namespace: synology-csi
type: Opaque
stringData:
  username: ${SYNOLOGY_USERNAME}  # DSM user account accessing the shared folder
  password: ${SYNOLOGY_PASSWORD}  # DSM user password accessing the shared folder
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-smb-storage
provisioner: csi.san.synology.com
parameters:
  protocol: "smb" # required for smb protocol
  # Before creating an SMB storage class, you must create a secret and specify the DSM user whom you want to give permissions to.
  csi.storage.k8s.io/node-stage-secret-name: "cifs-csi-credentials" # required for smb protocol
  csi.storage.k8s.io/node-stage-secret-namespace: "synology-csi"         # required for smb protocol
  # dsm: "1.1.1.1"
  location: '/volume1/k8s'
# mountOptions:
#   - dir_mode=0777
#   - file_mode=0777
#   - uid=0
#   - gid=0
reclaimPolicy: Retain
allowVolumeExpansion: true