---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: hook-succeeded
  name: synology-csi-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage # synology-synology-csi-delete
  resources:
    requests:
      storage: 1Gi

---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: test
  name: synology-csi-test
spec:
  template:
    metadata:
      labels:
        app: test
      name: synology-csi-test
    spec:
      containers:
        - name: touch
          command: [ "/bin/sh", "-c", "echo 'Hello world!' >/data/file" ]
          image: busybox
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: synology-csi-test
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "1000000"
    volumeMounts:
    - name: data
      mountPath: /data
      # subPath: busybox
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: synology-csi-test