allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
parameters:
  fsType: ext4
  location: '/volume1'
provisioner: csi.san.synology.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true